/**
 * shared/exports/index.mjs — Adviser-ready export pack
 *
 * Produces a print-optimised, adviser-ready bundle from a Case object:
 * cover sheet, chronology, deadlines, letters, documents checklist.
 */

import { formatDateForDisplay, calculateETDeadline } from '../deadlines/index.mjs';

/**
 * Generates an adviser-ready pack from a case.
 * Returns { html, sections } where html is a complete print-optimised document.
 */
export function generateAdviserPack(caseObj, options = {}) {
  if (!caseObj) return null;

  const sections = [];
  const now = new Date().toISOString().slice(0, 10);

  // Cover sheet
  const parties = (caseObj.parties || [])
    .map(
      (p) =>
        `${p.role}: ${p.name || ''}${p.org ? ` (${p.org})` : ''}${p.contact ? ` — ${p.contact}` : ''}`
    )
    .join('\n');

  sections.push({
    heading: 'Cover sheet',
    content: `
**Case:** ${caseObj.title}
**Jurisdiction:** ${caseObj.jurisdiction || 'UK'}
**Prepared:** ${formatDateForDisplay(now)}
${parties ? `**Parties:**\n${parties}` : ''}

*Prepared with information tools, not legal advice. Verify all dates, deadlines, and legal grounds against current official sources.*
    `.trim()
  });

  // Chronology
  if (caseObj.events && caseObj.events.length > 0) {
    const sorted = [...caseObj.events].sort((a, b) => a.date.localeCompare(b.date));
    const rows = sorted.map((e) => `| ${e.date} | ${e.type} | ${e.summary} |`).join('\n');
    sections.push({
      heading: 'Chronology',
      content: `| Date | Type | Summary |\n|------|------|---------|\n${rows}`
    });
  }

  // Deadlines
  if (caseObj.deadlines && caseObj.deadlines.length > 0) {
    const rows = caseObj.deadlines
      .map(
        (d) => `| ${d.ruleId} | ${d.startDate} | ${d.targetDate} | ${d.status} | ${d.note || ''} |`
      )
      .join('\n');
    sections.push({
      heading: 'Deadlines',
      content: `| Rule | Start | Target | Status | Note |\n|------|-------|--------|--------|------|\n${rows}`
    });
  }

  // Letters appendix
  if (caseObj.letters && caseObj.letters.length > 0) {
    const items = caseObj.letters
      .map(
        (l) =>
          `- **${l.templateId}** (from ${l.toolId}, rendered ${formatDateForDisplay(l.renderedAt)})`
      )
      .join('\n');
    sections.push({
      heading: 'Letters sent',
      content: items
    });
  }

  // Documents checklist
  if (caseObj.documents && caseObj.documents.length > 0) {
    const items = caseObj.documents
      .map((d) => `- [ ] ${d.name} (${d.kind})${d.note ? ` — ${d.note}` : ''}`)
      .join('\n');
    sections.push({
      heading: 'Documents checklist',
      content: items
    });
  }

  // Build HTML
  const sectionHtml = sections
    .map(
      (s) => `
    <section class="pack-section">
      <h2>${s.heading}</h2>
      ${s.content
        .split('\n')
        .filter((l) => l.trim())
        .map((l) => {
          if (l.startsWith('|')) return `<table>${parseTableRow(l)}</table>`;
          if (l.startsWith('- [')) return `<p>${l}</p>`;
          if (l.startsWith('**')) return `<p>${renderInlineMarkdown(l)}</p>`;
          return `<p>${renderInlineMarkdown(l)}</p>`;
        })
        .join('\n')}
    </section>
  `
    )
    .join('\n');

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(caseObj.title)} — Adviser Pack</title>
<style>
  @page { margin: 20mm; size: A4; }
  body { font-family: 'Iowan Old Style', 'Palatino', Georgia, serif; font-size: 12pt; line-height: 1.5; color: #1f1e1c; max-width: 180mm; margin: 0 auto; padding: 20mm 0; }
  h1 { font-size: 20pt; border-bottom: 2px solid #c2410c; padding-bottom: 8px; }
  h2 { font-size: 16pt; margin-top: 32px; color: #56524a; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 10pt; }
  th, td { border: 1px solid #8f8b80; padding: 6px 10px; text-align: left; }
  th { background: #f5f4ee; }
  p { margin: 8px 0; }
  .pack-section { page-break-inside: avoid; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #8f8b80; font-size: 9pt; color: #56524a; }
  @media print { body { padding: 0; } a { color: inherit; text-decoration: underline; } }
</style>
</head>
<body>
  <h1>${escapeHtml(caseObj.title)}</h1>
  ${sectionHtml}
  <div class="footer">
    <p>Generated by Open Access UK on ${formatDateForDisplay(now)}. Nothing was sent to a server.</p>
    <p>This is an information pack, not legal advice. Verify all content against current official sources.</p>
  </div>
</body>
</html>`;

  return { html, sections, title: caseObj.title };
}

function escapeHtml(str) {
  if (!str) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function renderInlineMarkdown(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/`(.+?)`/g, '<code>$1</code>');
}

function parseTableRow(markdownRow) {
  const cells = markdownRow
    .split('|')
    .filter(Boolean)
    .map((c) => c.trim());
  if (cells.length === 0) return '';
  const header = cells.map((c) => `<th>${escapeHtml(c)}</th>`).join('');
  return `<thead>${header}</thead>`;
}

/**
 * Generates a plain-text summary of a case for quick export.
 */
export function generateCaseSummary(caseObj) {
  if (!caseObj) return '';
  const lines = [
    `Case: ${caseObj.title}`,
    `Jurisdiction: ${caseObj.jurisdiction || 'UK'}`,
    `Events: ${(caseObj.events || []).length}`,
    `Deadlines: ${(caseObj.deadlines || []).length}`,
    `Documents: ${(caseObj.documents || []).length}`,
    `Letters: ${(caseObj.letters || []).length}`,
    '',
    '---',
    'Generated by Open Access UK.',
    'Not legal advice.'
  ];
  return lines.join('\n');
}

// Backwards compatibility aliases
export const createMarkdownDocument = generateAdviserPack;
export const createPrintDocument = (title, body) => ({
  title,
  body,
  generatedLocally: true,
  privacyNote: 'Generated locally in the browser.'
});

/**
 * Creates a safe filename from a title string.
 */
export function safeFilename(value = 'open-access-export', extension = 'txt') {
  const base = String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80);
  return `${base || 'open-access-export'}.${extension.replace(/^\./, '')}`;
}

/**
 * Creates a text export object with filename and mime type.
 */
export function createTextExport(title, body, options = {}) {
  const extension = options.extension || 'txt';
  const mimeType = extension === 'md' ? 'text/markdown;charset=utf-8' : 'text/plain;charset=utf-8';
  return {
    title,
    filename: safeFilename(title, extension),
    mimeType,
    content: String(body || '').trimEnd() + '\n'
  };
}
